version: '3.8'

services:
  solarman-bot:
    build: .
    container_name: solarman-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - SOLARMAN_TOKEN=${SOLARMAN_TOKEN}
    volumes:
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
    command: tail -f /dev/null  # Container stays running but does nothing
    # Cron jobs will run the container via docker-compose run 